var servicesSource = [
    {
        id:"admin-browser",
        description:"<p></p>",
        type:"rectangle",
        column:"1"
    },
    {
        id:"teller-browser",
        description:"<p></p>",
        type:"rectangle",
        column:"1"
    },
    {
        id:"task-scheduler",
        description:"<p></p>",
        type:"rectangle",
        column:"1"
    },
    {
        id:"customer-browser",
        description:"<p></p>",
        type:"rectangle",
        column:"1"
    },
    {
        id:"customer-mobile",
        description:"<p></p>",
        type:"rectangle",
        column:"1"
    },
    {
        id:"admin-teller-web-server",
        description:"<p></p>",
        type:"rectangle",
        column:"2"
    },
    {
        id:"core-banking",
        description:"<p></p>",
        type:"rectangle",
        column:"2"
    },
    {
        id:"mobile-web-server",
        description:"<p></p>",
        type:"rectangle",
        column:"2"
    },
    {
        id:"mobile-database",
        description:"<p></p>",
        type:"tube",
        column:"2"
    },
    {
        id:"app-database",
        description:"<p></p>",
        type:"tube",
        column:"3"
    },
    {
        id:"app-database-slave",
        description:"<p></p>",
        type:"tube",
        column:"3"
    },
    {
        id:"backup-system",
        description:"<p></p>",
        type:"rectangle",
        column:"3"
    },
    {
        id:"message-brocker",
        description:"<p></p>",
        type:"rectangle",
        column:"3"
    },   
    {
        id:"sms-gateway",
        description:"<p></p>",
        type:"rectangle",
        column:"3" 
    },
    {
        id:"mail-server",
        description:"<p></p>",
        type:"rectangle",
        column:"4"
    
    },
    {
        id:"backup-server",
        description:"<p></p>",
        type:"rectangle",
        column:"4"
    
    }
];